server:
  port: 6600
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    schema:
      - classpath:sql/init.sql
    initialization-mode: always
    platform: mysql
    sql-script-encoding: UTF-8

    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.42.119:3306/shop_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

    druid:
      #连接池初始化大小
      initial-size: 5
      #最小空闲连接数
      min-idle: 10
      #最大连接数
      max-active: 200

      # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1 FROM dual

      # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      web-stat-filter:
        enabled: true
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        url-pattern: /*
        #开启监控页面
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin


#Redis配置

  redis:
    database: 0  #Redis索引0~15，默认为0
    host: 192.168.42.119
    port: 6379
    password:  #密码（默认为空）
#    lettuce: # 这里标明使用lettuce配置
#      pool:
#        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 5     #连接池中的最大空闲连接
#        min-idle: 0     #连接池中的最小空闲连接
    timeout: 10000ms    #连接超时时间（毫秒）
swagger:
  enabled: true
  ip: localhost