server:
  port: 8686
spring:
  datasource:
    url: jdbc:mysql://192.168.42.118:3306/shop_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    druid:
      #连接池初始化大小
      initial-size: 5
      #最小空闲连接数
      min-idle: 10
      #最大连接数
      max-active: 200
      #不统计这些请求数据
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

      #访问监控网页的登录用户名和密码
      stat-view-servlet:
        login-username: druid
        login-password: druid
    servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB


swagger:
  enabled: true
  ip: localhost